### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by zhubinsheng** [chuili/ECDHKeyExchange#1]
KeyAgreement aKA = KeyAgreement.getInstance("ECDH", "SC");
            aKA.init(kpA.getPrivate());
            aKA.doPhase(kpA.getPublic(), true);
            SecretKey sharedKeyA = **aKA**.generateSecret("AES");
//            Log.d(TAG, "-----------[Shared key A generation - end]-----------");

            endMilis = System.currentTimeMillis();
            long sharedSecGenDuration = endMilis - beginMilis;
            Log.d(TAG, "Duration for shared secret generation: " + sharedSecGenDuration);

            // Generate shared secret B
//            Log.d(TAG, "-----------[Shared key B generation - start]-----------");
            KeyAgreement aKA2 = KeyAgreement.getInstance("ECDH", "SC");
            aKA2.init(kpB.getPrivate());
            aKA2.doPhase(kpB.getPublic(), true);
            SecretKey sharedKeyB = **_aKA_**.generateSecret("AES");

SecretKey sharedKeyA = **### aKA**.generateSecret("AES");
SecretKey sharedKeyB = **_aKA_**.generateSecret("AES");
tow _aKA_ : i think it is error code

**Comment by chuili** [comment]
Fixed, thanks.
